name: Daily AI News

on:
  schedule:
    - cron: '0 11 * * *'   # 08h00 BRT (11h00 UTC)
    - cron: '40 20 * * *'  # 17h40 BRT (20h40 UTC)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run daily news agent
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EMAIL_FROM:   ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:     ${{ secrets.EMAIL_TO }}
        run: |
          python send_ai_news.py
