name: Daily AI News

on:
  schedule:
    # 08:00 BRT (UTC−3) = 11:00 UTC
    - cron: '0 11 * * *'
    # 18:40 BRT (UTC−3) = 21:40 UTC
    - cron: '40 21 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13 (requerido pela OpenAI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install requests openai

      - name: Run daily news agent
        env:
          NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python ai_news_agent_openai.py
