name: Daily AI News (Versão Leve)

on:
  schedule:
    - cron: '0 11 * * *'     # 08:00 BRT
    - cron: '40 21 * * *'    # 18:40 BRT
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Set up Python 3.12 (recomendado para CrewAI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências mínimas
        run: |
          pip install --upgrade pip
          pip install \
            crewai==0.28.8 \
            langchain_community==0.0.29 \
            crewai_tools==0.1.6 \
            openai \
            requests

      - name: Executar versão leve do pipeline IA
        env:
          NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python ai_news_agents_email_pipeline_light.py
