name: Daily AI News

on:
  schedule:
    # 08:00 BRT (UTC−3) = 11:00 UTC
    - cron: '0 11 * * *'
    # 17:50 BRT (UTC−3) = 20:50 UTC
    - cron: '50 20 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install requests googletrans==4.0.0-rc1

      - name: Run daily news agent
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          EMAIL_FROM:   ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:     ${{ secrets.EMAIL_TO }}
        run: python send_ai_news.py
