name: Daily AI News

on:
  schedule:
    - cron: '0 11 * * *'     # 08:00 BRT
    - cron: '40 21 * * *'    # 18:40 BRT
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13 (requerido pela OpenAI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install basic dependencies
        run: pip install requests openai

      - name: Install full dependencies (CrewAI etc.)
        run: |
          pip install crewai==0.28.8 crewai_tools==0.1.6 \
                      langchain_community==0.0.29 openai serperdev requests

      - name: Run AI news pipeline
        env:
          NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python ai_news_agents_email_pipeline.py
