name: Daily AI News

on:
  schedule:
    - cron: '0 11 * * *'     # 08:00 BRT
    - cron: '40 21 * * *'    # 18:40 BRT
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install openai requests

      - name: Executar script de notícias IA
        env:
          NEWS_API_KEY:   ${{ secrets.NEWS_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          EMAIL_FROM:     ${{ secrets.EMAIL_FROM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_TO:       ${{ secrets.EMAIL_TO }}
        run: python ai_news_agent.py
